### ISSUE TITLE
Server crash with adding spawns to biomes, but works fine on clients

### ISSUE THREAD

**Issue by Golrith** [oldjunyi/NoMobSpawningOnTrees#16]
Servers are crashing when trying to add spawns:
        @biometype:MOUNTAIN, mob:Silverfish, weight:50
        @biometype:DRY, mob:techguns.alienbug, weight:5, count:1

error below. removing these commands and server loads fine.

Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from No Mob Spawning on Trees (nmsot)
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_185359_l()Ljava/lang/String;
	at com.mmyzd.nmsot.SpawnListManager.parse(SpawnListManager.java:126)
	at com.mmyzd.nmsot.rule.RuleSet.<init>(RuleSet.java:38)
	at com.mmyzd.nmsot.NoMobSpawningOnTrees.initialize(NoMobSpawningOnTrees.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)

**Comment by CaveAnon** [comment]
I am getting the same crash, using both (or either) of  `@biome:`or `@biometype:` commands when starting a multiplayer server. It runs fine (no errors) on singleplayer. 

Hopefully this can be fixed since this is honestly the main feature of the mod for me. 

Here's the crashlog:
```
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 2019-09-15 15:47:16 UTC
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from No Mob Spawning on Trees (nmsot)
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_185359_l()Ljava/lang/String;
    at com.mmyzd.nmsot.SpawnListManager.parse(SpawnListManager.java:126)
    at com.mmyzd.nmsot.rule.RuleSet.<init>(RuleSet.java:38)
    at com.mmyzd.nmsot.NoMobSpawningOnTrees.initialize(NoMobSpawningOnTrees.java:59)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
    at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:219)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 4.15.0-52-generic
  Java Version: 1.8.0_191, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 87958552 bytes (83 MB) / 537919488 bytes (513 MB) up to 2147483648 bytes (2048 MB)
  JVM Flags: 3 total; -Xmx2048M -Xms512M -XX:+UseG1GC
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 81 mods loaded, 81 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                   | Version            | Source                                             | Signature                                |
       |:----- |:-------------------- |:------------------ |:-------------------------------------------------- |:---------------------------------------- |
       | LCHI  | minecraft            | 1.12.2             | minecraft.jar                                      | None                                     |
       | LCHI  | mcp                  | 9.42               | minecraft.jar                                      | None                                     |
       | LCHI  | FML                  | 8.0.99.99          | custom.jar                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHI  | forge                | 14.23.5.2838       | custom.jar                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHI  | foamfixcore          | 7.7.4              | minecraft.jar                                      | None                                     |
       | LCHI  | movillages           | 1.5.4              | [1.12]MoVillages-1.5.4.jar                         | None                                     |
       | LCHI  | antiqueatlas         | 4.5.1              | antiqueatlas-1.12.2-4.5.1.jar                      | e631d7254e451d0360d0148cb21407d5511d45e9 |
       | LCHI  | applecore            | 3.2.0              | AppleCore-mc1.12.2-3.2.0.jar                       | None                                     |
       | LCHI  | baubles              | 1.5.2              | Baubles-1.12-1.5.2.jar                             | None                                     |
       | LCHI  | artifacts            | 1.12.2-1.1.0       | Artifacts-1.12.2-1.1.0.jar                         | None                                     |
       | LCHI  | crafttweaker         | 4.1.19             | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
       | LCHI  | mtlib                | 3.0.6              | MTLib-3.0.6.jar                                    | None                                     |
       | LCHI  | modtweaker           | 4.0.17             | modtweaker-4.0.17.jar                              | None                                     |
       | LCHI  | jei                  | 4.15.0.268         | jei_1.12.2-4.15.0.268.jar                          | None                                     |
       | LCHI  | quark                | r1.6-177           | Quark-r1.6-177.jar                                 | None                                     |
       | LCHI  | autoreglib           | 1.3-32             | AutoRegLib-1.3-32.jar                              | None                                     |
       | LCHI  | betterbuilderswands  | 0.11.1             | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar    | None                                     |
       | LCHI  | betterquesting       | 3.5.300            | BetterQuesting-3.5.300.jar                         | None                                     |
       | LCHI  | mantle               | 1.12-1.3.3.55      | Mantle-1.12-1.3.3.55.jar                           | None                                     |
       | LCHI  | traverse             | 1.6.0              | Traverse-1.12.2-1.6.0-69.jar                       | None                                     |
       | LCHI  | betterwithmods       | 1.12-2.3.20-1027   | BetterWithMods-1.12-2.3.20-1027.jar                | None                                     |
       | LCHI  | forgelin             | 1.8.3              | Forgelin-1.8.3.jar                                 | None                                     |
       | LCHI  | bountiful            | 2.2.0              | Bountiful-2.2.0.jar                                | None                                     |
       | LCHI  | carryon              | 1.12.1             | CarryOn+MC1.12.2+v1.12.1.jar                       | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
       | LCHI  | chameleon            | 1.12-4.1.3         | Chameleon-1.12-4.1.3.jar                           | None                                     |
       | LCHI  | champions            | 1.12.2-1.0.10.1    | champions-1.12.2-1.0.10.1.jar                      | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHI  | charm                | 1.12.2-1.1.12      | Charm-1.12.2-1.1.12.jar                            | None                                     |
       | LCHI  | combatrefined        | 1.4.1              | combatrefined-1.4.1.jar                            | None                                     |
       | LCHI  | sccraftingrunes      | 1.1                | craftingrunes-1.1.jar                              | None                                     |
       | LCHI  | craftstudioapi       | 1.0.0              | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
       | LCHI  | crafttweakerjei      | 2.0.3              | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
       | LCHI  | customstartinggear   | 1.2.0              | CustomStartingGear-1.12-1.2.0.9-universal.jar      | None                                     |
       | LCHI  | cyclopscore          | 1.5.0              | CyclopsCore-1.12.2-1.5.0.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCHI  | divergentunderground | 0.64.0             | Divergent-Underground-1.12-0.64.0.jar              | None                                     |
       | LCHI  | dungeontactics       | DT-0.16.6          | DungeonTactics-1.12.2-0.16.6.jar                   | None                                     |
       | LCHI  | ebwizardry           | 4.1.4              | Electroblob's+Wizardry+-+4.1.4+-+MC+1.12.2.jar     | None                                     |
       | LCHI  | embassy              | 5.0.0              | Embassy_5.0-b19.jar                                | None                                     |
       | LCHI  | fastfurnace          | 1.3.1              | FastFurnace-1.12.2-1.3.1.jar                       | None                                     |
       | LCHI  | fastleafdecay        | v14                | FastLeafDecay-v14.jar                              | None                                     |
       | LCHI  | fastbench            | 1.7.2              | FastWorkbench-1.12.2-1.7.2.jar                     | None                                     |
       | LCHI  | foamfix              | 0.10.5-1.12.2      | foamfix-0.10.5-1.12.2.jar                          | None                                     |
       | LCHI  | gravestone           | 1.10.2             | gravestone-1.10.2.jar                              | None                                     |
       | LCHI  | grimoireofgaia       | 1.6.9.3            | Grimoire of Gaia.jar                               | None                                     |
       | LCHI  | hardcorebuoy         | ${version}         | HardcoreBuoy-1.12-1.1.0.jar                        | None                                     |
       | LCHI  | hardcoredarkness     | 2.0                | HardcoreDarkness-MC1.12.2-2.0.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHI  | harvestersnight      | 1.1.0              | harvestersnight-1.12.2-1.1.0.jar                   | None                                     |
       | LCHI  | ichunutil            | 7.2.1              | iChunUtil-1.12.2-7.2.1.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHI  | inspirations         | 1.12.2-0.2.8       | Inspirations-1.12.2-0.2.8.jar                      | None                                     |
       | LCHI  | loottweaker          | 0.0.10             | LootTweaker-1.12.2-0.0.10.jar                      | None                                     |
       | LCHI  | llibrary             | 1.7.19             | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHI  | mowziesmobs          | 1.5.4              | mowziesmobs-1.5.4.jar                              | None                                     |
       | LCHI  | multimob             | 1.0.5              | multimob-1.0.5.jar                                 | None                                     |
       | LCHI  | naturalabsorption    | 1.0.0_for_mc1.12.2 | naturalabsorption-1.0.0_for_mc1.12.2.jar           | None                                     |
       | LCHE  | nmsot                | 1.2.2-mc1.12.2     | NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar            | None                                     |
       | LCH   | primitivemobs        | 1.2.3a             | primitivemobs-1.2.3a.jar                           | None                                     |
       | LCH   | pumpkincarving       | 1.4.0              | PumpkinCarving1.12-1.4.0.jar                       | None                                     |
       | LCH   | quarkoddities        | 1                  | QuarkOddities-1.12.2.jar                           | None                                     |
       | LCH   | realdrops            | 1.2.14             | RealisticItemDrops-1.2.14.jar                      | None                                     |
       | LCH   | roguelike            | 1.8.0              | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
       | LCH   | ruins                | 17.2               | Ruins-1.12.2.jar                                   | None                                     |
       | LCH   | rustic               | 1.1.1              | rustic-1.1.1.jar                                   | None                                     |
       | LCH   | silentlib            | 3.0.13             | SilentLib-1.12.2-3.0.13+167.jar                    | None                                     |
       | LCH   | scalinghealth        | 1.3.37             | ScalingHealth-1.12.2-1.3.40+145.jar                | None                                     |
       | LCH   | spartanshields       | 1.5.4              | SpartanShields-1.12.2-1.5.4.jar                    | None                                     |
       | LCH   | spartanweaponry      | beta 1.3.0         | SpartanWeaponry-1.12.2-beta-1.3.0.jar              | None                                     |
       | LCH   | specialai            | 1.1.0_for_mc1.12.2 | specialai-1.1.0_for_mc1.12.2.jar                   | None                                     |
       | LCH   | specialmobs          | 1.0.2_for_mc1.12.2 | specialmobs-1.0.2_for_mc1.12.2.jar                 | None                                     |
       | LCH   | bq_standard          | 3.4.159            | StandardExpansion-3.4.159.jar                      | None                                     |
       | LCH   | structuredcrafting   | 0.2.1              | StructuredCrafting-1.12.2-0.2.1.jar                | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | toolbelt             | 1.9.9              | ToolBelt-1.12.2-1.9.9.jar                          | None                                     |
       | LCH   | twilightforest       | 3.9.984            | twilightforest-1.12.2-3.9.984-universal.jar        | None                                     |
       | LCH   | vanillafix           | 1.0.10-SNAPSHOT    | VanillaFix-1.0.10-99.jar                           | None                                     |
       | LCH   | variedcommodities    | 1.12.2             | VariedCommodities_1.12.2(15may18.jar               | None                                     |
       | LCH   | villagenames         | 3.2.1              | VillageNames-1.12.2-3.2.1.jar                      | None                                     |
       | LCH   | vtt                  | 0.6.4              | VillagerTrades-1.12-0.6.4.jar                      | None                                     |
       | LCH   | waystones            | 4.0.67             | Waystones_1.12.2-4.0.67.jar                        | None                                     |
       | LCH   | wearablebackpacks    | 3.1.3              | WearableBackpacks-1.12.2-3.1.3.jar                 | None                                     |
       | LCH   | whatloomsahead       | 1.2.2              | whatloomsahead-1.12.2-1.2.2.jar                    | None                                     |
       | LCH   | worleycaves          | 1.5.0              | worleycaves-1.5.0.jar                              | None                                     |
       | LCH   | orelib               | 3.5.2.2            | OreLib-1.12.2-3.5.2.2.jar                          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCH   | phosphor-lighting    | 1.12.2-0.2.6       | phosphor-1.12.2-0.2.6+build50-universal.jar        | f0387d288626cc2d937daa504e74af570c52a2f1 |
  Loaded coremods (and transformers): ForgelinPlugin (Forgelin-1.8.3.jar)
                                        
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
                                        pw.prok.realbench.asm.RBTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      Quark Plugin (Quark-r1.6-177.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      CharmLoadingPlugin (Charm-1.12.2-1.1.12.jar)
                                        svenhjol.charm.base.CharmClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
                                        lumien.hardcoredarkness.asm.ClassTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      LoadingPlugin (HardcoreBuoy-1.12-1.1.0.jar)
                                        betterwithmods.core.ClassTransformer
  Pulsar/inspirations loaded Pulses: - InspirationsShared (Enabled/Forced)
                                     - InspirationsBuilding (Enabled/Not Forced)
                                     - InspirationsUtility (Enabled/Not Forced)
                                     - InspirationsTools (Enabled/Not Forced)
                                     - InspirationsRecipes (Enabled/Not Forced)
                                     - InspirationsTweaks (Enabled/Not Forced)
                                     - InspirationsShared (Enabled/Forced)
                                     - TwilightForestPlugin (Enabled/Not Forced)
  Suspected Mods: No Mob Spawning on Trees (nmsot)
  Profiler Position: N/A (disabled)
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)

```
